### ISSUE TITLE
fixed guide size?

### ISSUE THREAD

**Issue by klooj** [glepnir/indent-guides.nvim#10]
is it possible to use a fixed number of columns for the guide size without changing the calculation of shiftwidth  or tabwidth? while we wait for the nvim virtual text merge, I prefer the aesthetic of a 1 column indent-guide no matter the type or size of indents. I tried hard coding `guide_size` and using a decimal value and a negative value for `indent_guide_size`, but that all failed spectacularly. 

in other words, how do I make the second image resemble the first image without changing sw, tbs, [no]expandtab, etc.?
1. sw=2, expand tab:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/57016271/105879212-e3398a00-5fcf-11eb-88f0-941c619c9eca.png">
2. tbs=4, noexpandtab:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/57016271/105879505-40cdd680-5fd0-11eb-9f36-62449f00eeac.png">

Thank you!

**Comment by glepnir** [comment]
I will check it when the lspsaga.nvim stable.

**Comment by klooj** [comment]
preesh.

**Comment by glepnir** [comment]
tbs mean tabstop right?

**Comment by glepnir** [comment]
seems like works fine in a shell file 
![image](https://user-images.githubusercontent.com/41671631/106891259-69b73f80-6725-11eb-9399-dba17f0c84f5.png)

**Comment by klooj** [comment]
Whoops. Yes, I meant tabstop but said tbs instead of ts. And wow, shiftwidth just needed to be changed. I had it set it to match tabwidth by default. Thank you. 

Sidenote: lspsaga looks gorgeous and is generating some hype. i'm looking forward to giving it a spin.

**Comment by klooj** [comment]
as it turns out, what I want is not possible without virtual text. I thought adjusting shiftwidth fixed it, but when I retab! it highlights the full tabspace instead of just the first column. the issue is that the hard tab cannot be split into columns even just for highlighting without expanding it.
