### ISSUE TITLE
Add support for Indent Blankline

### ISSUE THREAD

**Issue by ahmedkhalf** [glepnir/indent-guides.nvim#11]
Hello, first of all thank you for making this amazing plugin, I really like the block indent style, and the async design.

My suggestion is to also add the indent on blank lines:
![image](https://user-images.githubusercontent.com/36672196/106162144-36af0200-61a1-11eb-9df8-26acc072f9f5.png)
I know one plugin which does this using lua: https://github.com/lukas-reineke/indent-blankline.nvim/tree/lua
So if this plugin can support it too, I would be very grateful.

Many thanks.

**Comment by glepnir** [comment]
check readem TODO，

**Comment by ahmedkhalf** [comment]
Hello, I don't think the pr did anything: there is still no indent char at the blank line:

![image](https://user-images.githubusercontent.com/36672196/109410476-66c20e80-79b4-11eb-9be4-eefcd35f7b05.png)

Please consider reopening this issue. @glepnir

**Comment by glepnir** [comment]
because it's false on default `indent_pretty_mode = false`. because there has some bug. so I set it to false in default options. when i fix some bug I will reset it to true in default.

**Comment by ahmedkhalf** [comment]
oh okay
