### ISSUE TITLE
The `exclude_filetypes` option does not work

### ISSUE THREAD

**Issue by yech1990** [glepnir/indent-guides.nvim#16]
![image](https://user-images.githubusercontent.com/5415510/108996191-0d6a8e80-76d9-11eb-92c6-1ea0a99cddde.png)

**Comment by yech1990** [comment]
```bash
$ nvim --version

NVIM v0.5.0-dev+1109-g6b7cc45c4
```

**Comment by glepnir** [comment]
you do not need to config this. because the indent guides support dashbaord filetype by default.

**Comment by yech1990** [comment]
So, how can I disable indent lines for dashboard filetype?

**Comment by glepnir** [comment]
you just push the options to there which you wan to change. remove the exclude filetype

**Comment by yech1990** [comment]
The indent line do no show up by using a previous version of indent-guides plugin.
![image](https://user-images.githubusercontent.com/5415510/108999572-718f5180-76dd-11eb-929a-18c8f703602c.png)

**Comment by yech1990** [comment]
Dose `exclude_filetypes` means do not show indent lines for listed filetypes?

**Comment by yech1990** [comment]
> you do not need to config this. because the indent guides support dashbaord filetype by default.

Do you mean indent guides **DO NOT** support by default?

**Comment by glepnir** [comment]
can't reproduce works for me.
![image](https://user-images.githubusercontent.com/41671631/109000401-a2bc5180-76de-11eb-9da6-4c54882c6909.png)

**Comment by yech1990** [comment]
It also work for me hours ago, before I upgrade the latest version of neovim and upgrade the plugins.

My configuration files are posted on github now. Could you please help me to figure out the problem?

**Comment by glepnir** [comment]
Hmm I just work with min config. so you need check the min config. and I had improve indent-guides. so maybe you can try the latest version

**Comment by yech1990** [comment]
oops... The latest version raise a more serious bug.
An error message pop up on start up and the color of indent lines are not consistent with my config.

![image](https://user-images.githubusercontent.com/5415510/109009906-1879ea80-76ea-11eb-95f9-b60c26684945.png)

**Comment by glepnir** [comment]
looks like you config some field that does not exist in default option.

**Comment by yech1990** [comment]
I just set the fields as the default settings. Could you help me debug on the latest version of neovim.
Seem that this bug take place after I upgrade neovim to latest version.

![Uploading image.png…]()

**Comment by glepnir** [comment]
I also use latest version neovim

![image](https://user-images.githubusercontent.com/41671631/109010767-28de9500-76eb-11eb-8f91-b6e63b1663d6.png)

**Comment by glepnir** [comment]
if the options value same as default. do not need to put it into setup function.

**Comment by yech1990** [comment]
I think these line in the configuration file might lead to the bug.

After removing these line, everything work as expected now.

![image](https://user-images.githubusercontent.com/5415510/109011258-aacebe00-76eb-11eb-9800-3f526dab9768.png)

**Comment by glepnir** [comment]
hmm no, I test it  works fine with me . so check the min config .

![image](https://user-images.githubusercontent.com/41671631/109011359-c20dab80-76eb-11eb-8ce8-991a929c55cb.png)

**Comment by yech1990** [comment]
> hmm no, I test it works fine with me . so check the min config .
> 
> ![image](https://user-images.githubusercontent.com/41671631/109011359-c20dab80-76eb-11eb-8ce8-991a929c55cb.png)

The colors of indent lines are red and green, but not "#23272e"

**Comment by glepnir** [comment]
looks like has some bug. check it tomorrow.

**Comment by cybaol** [comment]
I encountered the same problem that the exclusive filetypes are not work.

**Comment by huyvohcmc** [comment]
I have a similar issue with https://github.com/Yggdroot/indentLine/issues/315
