### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by ruifm** [glepnir/indent-guides.nvim#2]
Since 6b0b0524d81945b8c0806a14020ab2f93847210b everything (scrolling/editing/etc) is very very laggy.

Before this commit things were fine.

Love your plugin btw.

**Comment by glepnir** [comment]
@ruifm  How about now? notice that rename `default_opts` to `options`

**Comment by ruifm** [comment]
Works like a charm now! Thanks for the quick fix!

Looking forward for the new features
