### ISSUE TITLE
bugged newline guides?

### ISSUE THREAD

**Issue by fedoranvar** [glepnir/indent-guides.nvim#20]
At First, thank you for your work!

Secondly,
Recently, i've noticed extra guides on newlines (but not at all newlines - can't figure it out the cause)
![image](https://user-images.githubusercontent.com/52028706/109141258-5d039580-777f-11eb-8e7d-d2447301bca4.png)

and if I backspace it or move join next line to it, then it moves to the end of previous line or replace beggining of next line
![image](https://user-images.githubusercontent.com/52028706/109141481-99cf8c80-777f-11eb-90a5-3eacd76a9934.png)

or 

![image](https://user-images.githubusercontent.com/52028706/109141444-8d4b3400-777f-11eb-9f12-efba62b3920c.png)

Workaround:
had to move to `cbe28c6d` commit
At `85896f0f` - still can see this issue

**Comment by glepnir** [comment]
hmmm  the second and third pic is an known bug. the first is wired

**Comment by fedoranvar** [comment]
it seems it was resolved.

Thanks!
