### ISSUE TITLE
feature request: Only show indent guides inside of loops, functions, etc

### ISSUE THREAD

**Issue by sp1n0r** [glepnir/indent-guides.nvim#21]
I have no idea yet how to achieve this. Similarly to vscode it should only display the indent guides inside of loops, functions, if statements, etc. I'll provide an example:

How indent-guides.nvim and other similar plugins do it:
``` c
#include <stdio.h>
int main(int args, char **argv)
{
|   char A = 'A';
|   |
|   for (int i = 0; i < 10; i++)
|   {
|   |   printf("%c", A);
|   |   |
|   |   printf("%d", i);
|   }
|   |
|   return 0;
}
```

How vscode does it:
``` c
#include <stdio.h>
int main(int args, char **argv)
{
|   char A = 'A';
|
|   for (int i = 0; i < 10; i++)
|   {
|   |   printf("%c", A);
|   |
|   |   printf("%d", i);
|   }
|
|   return 0;
}
```

It's subtle but in bigger projects it makes a great difference. I don't know how this could be achieved but if it's possible somewhere it's in neovim. The hard part is that it may vary from language to language, Python doesn't use `{}`, etc.

**Comment by glepnir** [comment]
Indent guides works like this.

![image](https://user-images.githubusercontent.com/41671631/109154269-06ab4c80-77a9-11eb-8943-1286bc8b0863.png)

**Comment by sp1n0r** [comment]
Oh wow I had no idea. Since other plugins don't work like that that's why I stopped using them. Now the only thing holding me back a little is the ability to change the character

**Comment by sp1n0r** [comment]
If it's not too hard I'll try to implement it. Well I'll close the issue since it seems that it's already been solved :p
