### ISSUE TITLE
Cursor dissapear in odd columns with termguicolors on

### ISSUE THREAD

**Issue by pedro757** [glepnir/indent-guides.nvim#25]
**When I have termguicolors on** cursor change color in odd columns

This is an odd column
![image](https://user-images.githubusercontent.com/30637426/112335625-c6999580-8c92-11eb-81cf-a2b81d640fb1.png)

This is an even column
![image](https://user-images.githubusercontent.com/30637426/112336208-43c50a80-8c93-11eb-9a24-62ea247ab745.png)

**When I have termguicolors off** is even worse because it show three column colors, it's a little bit distracting; Cursor is not visible either.
![image](https://user-images.githubusercontent.com/30637426/112338599-4de80880-8c95-11eb-9879-0f4fbb03fea0.png)

I use Neovim version 0.5.0-dev+1175-g1186f7dd9
Alacritty v7.2
$TERM = screen-256color
$COLORTERM truecolor

I try the same on kitty and it works, so the problem is with alacritty, gnome terminal,

**Comment by pedro757** [comment]
Sorry, I solved this by fixing text color and cursor color in alacritty config

```yml
# ~/.config/alacritty/alacritty.yml
colors:
  cursor:
    text: '#000000'
    cursor: '#ebdbb3'
```
Now cursor does not disappear
![image](https://user-images.githubusercontent.com/30637426/112738573-5614a200-8f3a-11eb-840f-b210b999a2f8.png)

**Comment by afreakk** [comment]
I have the same issue, using alacritty with `gruvbox dark` from https://github.com/alacritty/alacritty/wiki/Color-schemes
