### ISSUE TITLE
Option to disable by default

### ISSUE THREAD

**Issue by languitar** [glepnir/indent-guides.nvim#26]
I'd like to use indent guides only occasionally. Is there an option to not render the guides by default?

**Comment by glepnir** [comment]
hmm you can disable it by command

**Comment by languitar** [comment]
Using an autocmd in every buffer? Sounds a bit wasteful to first render things simply disable it immediately.

**Comment by glepnir** [comment]
maybe can add an option to disable it :) support it later.

**Comment by languitar** [comment]
The original vim plugin has the option `indent_guides_enable_on_vim_startup` for this purpose, defaulting to being disable.

**Comment by glepnir** [comment]
this option work with `VimEnter` .that mean when you open vim it will do this command. now use 

`indent_enable = false ` to disable it.

**Comment by languitar** [comment]
Thanks, now I have this in my config:

```lua
local ig = require('indent_guides')
ig.setup({
  indent_start_level = 2,
  indent_enable = false,
})
```

Indent guides do not show up at start anymore. But `:indentGuidesToggle` also doesn't show them anymore. No errors reported though.

**Comment by glepnir** [comment]
aha..need fix.
