### ISSUE TITLE
Plan to follow setup convention?

### ISSUE THREAD

**Issue by carlitux** [glepnir/indent-guides.nvim#8]
Hi,

I am using packer and addpack breaks the plugin, would be good to have the setup function.

Thanks!.

**Comment by glepnir** [comment]
hmm you mean that indent-guides doesn't work with packer?

**Comment by carlitux** [comment]
yes I had to add these lines

```vim
autocmd BufRead,BufNewFile * IndentGuidesDisable
autocmd BufEnter * IndentGuidesEnable
```

to get working the indent

**Comment by glepnir** [comment]
Does this can't work?

 `use {'glepnir/indent-guides.nvim', opt = true,event = 'BufReadPre *'}`

**Comment by carlitux** [comment]
still the same issue, only show the first guide.

**Comment by glepnir** [comment]
Seems like packer does not load `plugin/indent_guides.vim`

**Comment by glepnir** [comment]
rewrite setup.
